CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    description VARCHAR(255),
    available BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE events_categories (
    event_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    CONSTRAINT pk_events_categories PRIMARY KEY (event_id, category_id),
    CONSTRAINT fk_events_categories_event FOREIGN KEY (event_id) REFERENCES events(id),
    CONSTRAINT fk_events_categories_category FOREIGN KEY (category_id) REFERENCES categories(id)
);
